pool:
  VmImage:ubuntu-20.04
Stages:
  stage: continuous_integration
  displayName: Continuous Integration
  jobs:
    job: build
    displayName: Build
    container: ncr.microsoft.com/dotnet/sdk:6.0
    steps:
      script: dotnet run 
        displayName: Run .NET application


